package abc.entity;
// Generated Apr 18, 2018 11:58:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Departs generated by hbm2java
 */
@Entity
@Table(name="departs"
    ,catalog="abc_company"
)
public class Departs  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set<Staffs> staffses = new HashSet<Staffs>(0);

    public Departs() {
    }

    public Departs(String name, Set<Staffs> staffses) {
       this.name = name;
       this.staffses = staffses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="departs")
    public Set<Staffs> getStaffses() {
        return this.staffses;
    }
    
    public void setStaffses(Set<Staffs> staffses) {
        this.staffses = staffses;
    }




}


