package abc.entity;
// Generated Apr 18, 2018 11:58:33 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Records generated by hbm2java
 */
@Entity
@Table(name="records"
    ,catalog="abc_company"
)
public class Records  implements java.io.Serializable {


     private Integer id;
     private Staffs staffs;
     private Boolean type;
     private String reason;
     private Date date;

    public Records() {
    }

    public Records(Staffs staffs, Boolean type, String reason, Date date) {
       this.staffs = staffs;
       this.type = type;
       this.reason = reason;
       this.date = date;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="staffusername")
    public Staffs getStaffs() {
        return this.staffs;
    }
    
    public void setStaffs(Staffs staffs) {
        this.staffs = staffs;
    }

    
    @Column(name="type")
    public Boolean getType() {
        return this.type;
    }
    
    public void setType(Boolean type) {
        this.type = type;
    }

    
    @Column(name="reason", length=100)
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date", length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


