package abc.entity;
// Generated Apr 18, 2018 11:58:33 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Staffs generated by hbm2java
 */
@Entity
@Table(name="staffs"
    ,catalog="abc_company"
    , uniqueConstraints = {@UniqueConstraint(columnNames="email"), @UniqueConstraint(columnNames="phone")} 
)
public class Staffs  implements java.io.Serializable {


     private String username;
     private Departs departs;
     private String password;
     private String name;
     private String gender;
     private Date birthday;
     private String photo;
     private String email;
     private String phone;
     private double salary;
     private String notes;
     private boolean role;
     private Set<Records> recordses = new HashSet<Records>(0);

    public Staffs() {
    }

	
    public Staffs(String username, String password, String name, String gender, Date birthday, String email, String phone, double salary, boolean role) {
        this.username = username;
        this.password = password;
        this.name = name;
        this.gender = gender;
        this.birthday = birthday;
        this.email = email;
        this.phone = phone;
        this.salary = salary;
        this.role = role;
    }
    public Staffs(String username, Departs departs, String password, String name, String gender, Date birthday, String photo, String email, String phone, double salary, String notes, boolean role, Set<Records> recordses) {
       this.username = username;
       this.departs = departs;
       this.password = password;
       this.name = name;
       this.gender = gender;
       this.birthday = birthday;
       this.photo = photo;
       this.email = email;
       this.phone = phone;
       this.salary = salary;
       this.notes = notes;
       this.role = role;
       this.recordses = recordses;
    }
   
     @Id 

    
    @Column(name="username", unique=true, nullable=false, length=100)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="departid")
    public Departs getDeparts() {
        return this.departs;
    }
    
    public void setDeparts(Departs departs) {
        this.departs = departs;
    }

    
    @Column(name="password", nullable=false, length=100)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="name", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="gender", nullable=false, length=6)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="birthday", nullable=false, length=10)
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    
    @Column(name="photo", length=100)
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    
    @Column(name="email", unique=true, nullable=false, length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="phone", unique=true, nullable=false, length=100)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="salary", nullable=false, precision=100)
    public double getSalary() {
        return this.salary;
    }
    
    public void setSalary(double salary) {
        this.salary = salary;
    }

    
    @Column(name="notes", length=100)
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }

    
    @Column(name="role", nullable=false)
    public boolean isRole() {
        return this.role;
    }
    
    public void setRole(boolean role) {
        this.role = role;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="staffs")
    public Set<Records> getRecordses() {
        return this.recordses;
    }
    
    public void setRecordses(Set<Records> recordses) {
        this.recordses = recordses;
    }




}


